# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrewMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('notes', models.CharField(max_length=35)),
                ('region', models.CharField(choices=[('Latin America', 'Latin America'), ('Oceania', 'Oceania'), ('Africa', 'Africa')], max_length=25)),
                ('farm', models.CharField(max_length=25)),
                ('altitude', models.CharField(max_length=35)),
                ('process', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('img', models.ImageField(default='coffee_images/default_coffee_image.whatever', upload_to='coffee_images/')),
                ('brew_method', models.ForeignKey(choices=[('Chemex', 'Chemex'), ('V60', 'V60'), ('Kalita Wave', 'Kalita Wave'), ('Aeropress', 'Aeropress')], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffees', to='coffee_book.BrewMethod')),
                ('shop_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('coffee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='coffee_book.Coffee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
