# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 21:33
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrewMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('notes', models.CharField(max_length=35)),
                ('region', models.CharField(choices=[('Latin America', 'Latin America'), ('Oceania', 'Oceania'), ('Africa', 'Africa')], max_length=25)),
                ('farm', models.CharField(max_length=25)),
                ('altitude', models.CharField(max_length=35)),
                ('process', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('img', models.ImageField(default='coffee_images/default_coffee_image.whatever', upload_to='coffee_images/')),
                ('brew_method', models.ForeignKey(choices=[('Chemex', 'Chemex'), ('V60', 'V60'), ('Kalita Wave', 'Kalita Wave'), ('Aeropress', 'Aeropress')], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffees', to='coffee_book.BrewMethod')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('coffee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='coffee_book.Coffee')),
            ],
        ),
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coffee',
            name='shop_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffees', to='coffee_book.ShopUser'),
        ),
    ]
