# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='shop_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
