# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_book', '0002_auto_20160916_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='shop_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
